# Generated by Django 3.2.6 on 2021-08-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drawing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='file_type',
            field=models.CharField(default='dwg', max_length=256),
        ),
    ]
