# Generated by Django 3.2.6 on 2021-08-05 05:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('Drawing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawing', to='Client.client'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
