# Generated by Django 3.2.6 on 2021-08-05 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drawing', '0002_auto_20210805_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
