# Generated by Django 3.2.6 on 2021-08-05 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drawing', '0002_auto_20210805_1426'),
        ('Part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='drawing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='Drawing.drawing'),
        ),
    ]
