# Generated by Django 3.2.6 on 2021-08-20 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OS_Part',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Part.part')),
                ('material_price', models.CharField(max_length=256)),
                ('milling_price', models.CharField(max_length=256)),
                ('heat_treat_price', models.CharField(max_length=256)),
            ],
            bases=('Part.part',),
        ),
        migrations.AlterField(
            model_name='part',
            name='material',
            field=models.CharField(choices=[('SKS3', 'SKS3'), ('KP4', 'KP4'), ('SKD61', 'SKD61')], default='SKS3', max_length=256),
        ),
    ]
