# Generated by Django 3.2.8 on 2021-12-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='business_id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='client',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='client',
            name='manager_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='manager_tel',
        ),
        migrations.RemoveField(
            model_name='client',
            name='note',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_bank',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_bank_account',
        ),
        migrations.RemoveField(
            model_name='client',
            name='representative',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tel',
        ),
    ]
