# Generated by Django 3.2.6 on 2021-08-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Division', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='main_division',
        ),
        migrations.RemoveField(
            model_name='division',
            name='sub_division',
        ),
        migrations.AddField(
            model_name='division',
            name='code',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
