# Generated by Django 3.2.5 on 2021-08-01 07:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('contact', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('main_division', models.IntegerField()),
                ('sub_division', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('created_at', models.DateField(default=datetime.date(2021, 8, 1))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='JIM.client')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=256)),
                ('y', models.CharField(max_length=256)),
                ('z', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('material', models.CharField(choices=[('SKS3', 'SKS3'), ('SKD61', 'SKD61'), ('KP1', 'KP1')], default='SKS3', max_length=256)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JIM.division')),
                ('drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JIM.drawing')),
            ],
        ),
    ]
