# Generated by Django 3.2.5 on 2021-08-01 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 8, 1)),
        ),
    ]
