# Generated by Django 3.2.5 on 2021-08-01 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JIM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing', to='JIM.client'),
        ),
    ]
