# Generated by Django 3.2.6 on 2021-08-02 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JIM', '0002_alter_drawing_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 8, 2)),
        ),
    ]
